apiVersion: v1
kind: Service
metadata:
  name: ng-gateway-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ng-gateway-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-gateway-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ng-gateway-api
    spec:
      containers:
      - name: ng-gateway-api
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        env:
          - name: ACCOUNT_SERVICE
            value: ng-auth-service:80
          - name: BOOK_SERVICE
            value: ng-book-service:80
          - name: CATALOG_SERVICE
            value: ng-catalog-service:80
        ports:
        - containerPort: 8080
          name: ng-gateway-api
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m