apiVersion: v1
kind: Service
metadata:
  name: ng-auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: ng-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ng-auth
    spec:
      containers:
      - name: ng-auth
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m